### ISSUE TITLE
Encryption of the phone fail

### ISSUE THREAD

**Issue by nikel123** [KonstaT/android_device_zte_kis3#1]
Encryption of the Phone is not possable, vold dies with pagefault. Dmesg:

<7>[  407.347630] vold: unhandled page fault (11) at 0x0000003c, code 0x005
<1>[  407.347644] pgd = dd12c000
<1>[  407.349574] [0000003c] *pgd=00000000
<6>[  407.352889] 
<6>[  407.352899] Pid: 347, comm:                 vold
<6>[  407.352910] CPU: 1    Tainted: G         C    (3.4.0-g32af937 #1)
<6>[  407.352921] PC is at 0xb6f62d02
<6>[  407.352929] LR is at 0xb6f648ef
<6>[  407.352938] pc : [<b6f62d02>]    lr : [<b6f648ef>]    psr: 600e0030
<6>[  407.352942] sp : b67f86d8  ip : b67f8220  fp : 00000000
<6>[  407.352950] r10: b67fc930  r9 : b67fc7b0  r8 : b660d028
<6>[  407.352958] r7 : b67fc804  r6 : 00000003  r5 : 00000910  r4 : ffffffff
<6>[  407.352967] r3 : 62875d5c  r2 : 62875d5c  r1 : b67f81e8  r0 : 00000000
<6>[  407.352977] Flags: nZCv  IRQs on  FIQs on  Mode USER_32  ISA Thumb  Segment user
<6>[  407.352987] Control: 10c5387d  Table: 1d12c06a  DAC: 00000015
<6>[  407.353022] [<c010cefc>](unwind_backtrace+0x0/0x134) from [<c0112b6c>](__do_user_fault+0x140/0x144)
<6>[  407.353042] [<c0112b6c>](__do_user_fault+0x140/0x144) from [<c090d210>](do_page_fault+0x2ac/0x438)
<6>[  407.353060] [<c090d210>](do_page_fault+0x2ac/0x438) from [<c01002c8>](do_DataAbort+0x38/0x98)
<6>[  407.353079] [<c01002c8>](do_DataAbort+0x38/0x98) from [<c090ba34>](__dabt_usr+0x34/0x40)
<6>[  407.353089] Exception stack(0xdd3d1fb0 to 0xdd3d1ff8)
<6>[  407.353099] 1fa0:                                     00000000 b67f81e8 62875d5c 62875d5c
<6>[  407.353112] 1fc0: ffffffff 00000910 00000003 b67fc804 b660d028 b67fc7b0 b67fc930 00000000
<6>[  407.353124] 1fe0: b67f8220 b67f86d8 b6f648ef b6f62d02 600e0030 ffffffff
<7>[  407.353601] vold: unhandled page fault (11) at 0x0000003c, code 0x005
<1>[  407.353612] pgd = dd12c000
<1>[  407.355581] [0000003c] *pgd=00000000
<6>[  407.359583] 
<6>[  407.359600] Pid: 347, comm:                 vold
<6>[  407.359611] CPU: 1    Tainted: G         C    (3.4.0-g32af937 #1)
<6>[  407.359624] PC is at 0xb6f62d02
<6>[  407.359631] LR is at 0xb6f648ef
<6>[  407.359641] pc : [<b6f62d02>]    lr : [<b6f648ef>]    psr: 600e0030
<6>[  407.359645] sp : b67f86d8  ip : b67f8220  fp : 00000000
<6>[  407.359653] r10: b67fc930  r9 : b67fc7b0  r8 : b660d028
<6>[  407.359661] r7 : b67fc804  r6 : 00000003  r5 : 00000910  r4 : ffffffff
<6>[  407.359671] r3 : 62875d5c  r2 : 62875d5c  r1 : b67f81e8  r0 : 00000000
<6>[  407.359682] Flags: nZCv  IRQs on  FIQs on  Mode USER_32  ISA Thumb  Segment user
<6>[  407.359693] Control: 10c5387d  Table: 1d12c06a  DAC: 00000015
<6>[  407.359746] [<c010cefc>](unwind_backtrace+0x0/0x134) from [<c0112b6c>](__do_user_fault+0x140/0x144)
<6>[  407.359771] [<c0112b6c>](__do_user_fault+0x140/0x144) from [<c090d210>](do_page_fault+0x2ac/0x438)
<6>[  407.359789] [<c090d210>](do_page_fault+0x2ac/0x438) from [<c01002c8>](do_DataAbort+0x38/0x98)
<6>[  407.359809] [<c01002c8>](do_DataAbort+0x38/0x98) from [<c090ba34>](__dabt_usr+0x34/0x40)
<6>[  407.359819] Exception stack(0xdd3d1fb0 to 0xdd3d1ff8)
<6>[  407.359831] 1fa0:                                     00000000 b67f81e8 62875d5c 62875d5c
<6>[  407.359844] 1fc0: ffffffff 00000910 00000003 b67fc804 b660d028 b67fc7b0 b67fc930 00000000
<6>[  407.359856] 1fe0: b67f8220 b67f86d8 b6f648ef b6f62d02 600e0030 ffffffff
<6>[  407.404623] vold (5873): undefined instruction: pc=b6cfbb08

And dmesg has also problems:

<6>[  423.425362] dmesg (5876): undefined instruction: pc=b6dcfb08
<6>[  423.425381] Code: e320f000 e320f000 f26001f0 e12fff1e (ec510f1e) 
<6>[  438.215417] dmesg (5877): undefined instruction: pc=b6e26b08
<6>[  438.215450] Code: e320f000 e320f000 f26001f0 e12fff1e (ec510f1e) 

It is possable, that compiler flags are not fully compatable with the cpu of Open C.

Other then what, image cm-12-20141120-UNOFFICIAL-KonstaKANG-kis3.zip ist pretty stable.

**Comment by KonstaT** [comment]
There could be a dozen things wrong at this point. It's still very early days of CM12 and this is not exactly on top of the priority list (haven't even bothered to test device encryption myself yet).

**Comment by KonstaT** [comment]
Encryption works on cm-12-20141221-UNOFFICIAL-KonstaKANG-kis3 build.
