### ISSUE TITLE
Fully Charged Issue

### ISSUE THREAD

**Issue by ajarmoszuk** [KonstaT/android_device_zte_kis3#2]
When fully charged, the phone does not respond to hardware buttons, the notification light is frozen at green even when unplugged and hard reset via battery removal is required.

**Comment by KonstaT** [comment]
Which ROM? What device variant?

I've never experienced such issue myself.

**Comment by ajarmoszuk** [comment]
ZTE Open C (Zte Kis III), cm-12-20141221-UNOFFICIAL-KonstaKANG-kis3

**Comment by KonstaT** [comment]
Does that happen on any other ROMs? AC/USB charging? Logs (logcat, dmesg)? Are you sure this is related to charging? Can you reproduce this every time battery is fully charged?

I just released that build couple of hours ago anyway. :o I fully charged on my yesterday's build and it didn't freeze. There were no notable changes after that.

**Comment by ajarmoszuk** [comment]
No logs left, only happens via AC charging as far as I can tell, maybe because I'm using a higher amperage charger, will try with standard 1AMP and report back.

**Comment by KonstaT** [comment]
I use a Samsung 2A charger. My original ZTE charger has an UK plug so I couldn't test it here in Finland anyway.

Fully charged my device with release build and nothing happened. It's more likely you just had some random glitch that has nothing to do with charging. I'm closing this as it's not something that can be reproduced.
