### ISSUE TITLE
device is only charging when shutdown

### ISSUE THREAD

**Issue by tristan-k** [KonstaT/android_device_zte_kis3#3]
**Firmware:** CyanogenMod 11 (Android 4.4.4)
**Recovery:** TWRP 2.8.5.0 for ZTE Open C / Kis 3
**Device:** ZTE Open C / Kis 3.

**Issue:** The device will only charge the battery when shutdown, otherwise discharging continues but AC Power is detected. I'm using the official AC Power Adapter.
### AC Power Adapter plugged in

![screen_plugged_in](https://cloud.githubusercontent.com/assets/732025/9760506/0baec2a4-56f6-11e5-86b0-326a39e8abc7.png)
### AC Power Adapter plugged out

![screen_plugged_out](https://cloud.githubusercontent.com/assets/732025/9760519/27db7ad0-56f6-11e5-8f5f-a0a9c3d68a0a.png)

**Comment by KonstaT** [comment]
You have disabled USB charging (Settings -> Developer option -> USB charging).

**Comment by tristan-k** [comment]
Well, that was embarrassing. Thanks for pointing it out!
