### ISSUE TITLE
Merge changes in older branches (example: cm11) with latest commits in upstream repositories

### ISSUE THREAD

**Issue by JuniorJPDJ** [KonstaT/android_device_zte_kis3#5]
Can you do this?
I need cm11 and want to have security updates applied

**Comment by KonstaT** [comment]
Nothing security update related goes into this tree.

I've already pushed all kernel CVE patches in cm-11.0/cm-12.1/cm-13.0 branches (see e.g. https://github.com/KonstaT/android_kernel_zte_msm8610/commits/cm-11.0). Android security patches are still merged into CM upstream (current patch level with CM11: 1 November 2016).
