### ISSUE TITLE
sepolicy: qseecomd denied

### ISSUE THREAD

**Issue by Sash0k** [KonstaT/android_device_zte_kis3#6]
Hi, _KonstaT_! I'm building lineage 14.1 from scratch with your device tree and vendor files.
Everything is ok except one minor issue: service **qseecomd** failed to start.
Here is dmesg:

> [ 4015.270628] init: Starting service 'qseecomd'...
> [ 4015.356504] type=1400 audit(1521055883.826:920): avc: denied { read write } for pid=6269 comm="qseecomd" name="mmcblk0rpmb" dev="tmpfs" ino=5942 scontext=u:r:tee:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file permissive=0
> [ 4015.380022] init: Service 'qseecomd' (pid 6269) exited with status 255
> [ 4015.385533] init: Service 'qseecomd' (pid 6269) killing any children in process group
> 
> [ 4020.401335] init: Starting service 'qseecomd'...
> [ 4020.485528] type=1400 audit(1521055888.956:921): avc: denied { read write } for pid=6270 comm="qseecomd" name="mmcblk0rpmb" dev="tmpfs" ino=5942 scontext=u:r:tee:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file permissive=0
> [ 4020.509406] init: Service 'qseecomd' (pid 6270) exited with status 255
> [ 4020.514919] init: Service 'qseecomd' (pid 6270) killing any children in process group
> ...

Now I down into selinux, but can't fix it yet. Could you help me?
Or can I disable proprietary **qseecomd** inside **init.target.rc**?

**Comment by KonstaT** [comment]
You're missing this patch. https://github.com/legaCyMod/android_local_manifest/blob/cm-13.0/patches/device_qcom_sepolicy/0001-sepolicy-hey-don-t-forget-msm8610.patch
