### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by bidaian** [KonstaT/android_device_zte_kis3#7]
Hi,

I followed the readme in this repository on a new empty folder.

`repo init -u git://github.com/LineageOS/android.git -b cm-14.1
curl --create-dirs -L -o .repo/local_manifests/manifest_zte_kis3.xml -O -L https://raw.githubusercontent.com/legaCyMod/android_local_manifest/cm-14.1/manifest_zte_kis3.xml
repo sync
. build/envsetup.sh
brunch kis3
`

And the build process stops with this error (see below). Any idea of what could be wrong?

`target Prebuilt:  (/home/edu/src/cm-11/out/target/product/kis3/kernel)
Gyp action: Generating JNI bindings from  /home/edu/src/cm-11/prebuilts/sdk/18/android.jar/android/view/Surface.class (/home/edu/src/cm-11/out/target/product/kis3/obj/GYP/shared_intermediates/ui/gl/jni/Surface_jni.h)
Traceback (most recent call last):
  File "../../base/android/jni_generator/jni_generator.py", line 1109, in <module>
    sys.exit(main(sys.argv))
  File "../../base/android/jni_generator/jni_generator.py", line 1105, in main
    GenerateJNIHeader(input_file, output_file, options)
  File "../../base/android/jni_generator/jni_generator.py", line 1018, in GenerateJNIHeader
    jni_from_javap = JNIFromJavaP.CreateFromClass(input_file, options)
  File "../../base/android/jni_generator/jni_generator.py", line 523, in CreateFromClass
    jni_from_javap = JNIFromJavaP(stdout.split('\n'), options)
  File "../../base/android/jni_generator/jni_generator.py", line 489, in __init__
    signature=JniParams.ParseJavaPSignature(contents[lineno + 1]))]
  File "../../base/android/jni_generator/jni_generator.py", line 148, in ParseJavaPSignature
    return '"%s"' % signature_line[signature_line.index(prefix) + len(prefix):]
ValueError: substring not found
make: *** [/home/edu/src/cm-11/out/target/product/kis3/obj/GYP/shared_intermediates/ui/gl/jni/Surface_jni.h] Error 1
`

**Comment by KonstaT** [comment]
Quick Google search tells this is because 'you don't have javap available in your $PATH.'

**Comment by bidaian** [comment]
Thanks @KonstaT . I had javap, but it was mismatched (openjdk-8 for javap and oracle-6 for the rest). If anyone has a similar problem and lands here, instead of doing update-alternatives for each one of java, javac, ... (in Debian/Ubuntu), it's better to change PATH and JAVA_HOME as in:

`export PATH=/usr/lib/jvm/jdk-6-oracle-x64/bin:$PATH

export JAVA_HOME=/usr/lib/jvm/jdk-6-oracle-x64
`
